language: node_js
dist: trusty
sudo: required

node_js:
  - '8'

services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - yarn install

script:
  - yarn test
